version: '3.8'
services:
    elasticsearch:
        image: elasticsearch:7.14.1
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: aden
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: aden
            ME_CONFIG_MONGODB_URL: mongodb://root:aden@mongo:27017/
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: aden
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    redis:
        image: redis:alpine
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - "15672:15672"
